export const emoji = {'1000': {'index': 0, 'body': '💯'
    }, '12340': {'index': 1, 'body': '🔢'
    }, 'grinning0': {'index': 2, 'body': '😀'
    }, 'grimacing0': {'index': 3, 'body': '😬'
    }, 'grin0': {'index': 4, 'body': '😁'
    }, 'joy0': {'index': 5, 'body': '😂'
    }, 'rofl0': {'index': 6, 'body': '🤣'
    }, 'partying0': {'index': 7, 'body': '🥳'
    }, 'smiley0': {'index': 8, 'body': '😃'
    }, 'smile0': {'index': 9, 'body': '😄'
    }, 'sweat_smile0': {'index': 10, 'body': '😅'
    }, 'laughing0': {'index': 11, 'body': '😆'
    }, 'innocent0': {'index': 12, 'body': '😇'
    }, 'wink0': {'index': 13, 'body': '😉'
    }, 'blush0': {'index': 14, 'body': '😊'
    }, 'slightly_smiling_face0': {'index': 15, 'body': '🙂'
    }, 'upside_down_face0': {'index': 16, 'body': '🙃'
    }, 'relaxed0': {'index': 17, 'body': '☺️'
    }, 'yum0': {'index': 18, 'body': '😋'
    }, 'relieved0': {'index': 19, 'body': '😌'
    }, 'heart_eyes0': {'index': 20, 'body': '😍'
    }, 'smiling_face_with_three_hearts0': {'index': 21, 'body': '🥰'
    }, 'kissing_heart0': {'index': 22, 'body': '😘'
    }, 'kissing0': {'index': 23, 'body': '😗'
    }, 'kissing_smiling_eyes0': {'index': 24, 'body': '😙'
    }, 'kissing_closed_eyes0': {'index': 25, 'body': '😚'
    }, 'stuck_out_tongue_winking_eye0': {'index': 26, 'body': '😜'
    }, 'zany0': {'index': 27, 'body': '🤪'
    }, 'raised_eyebrow0': {'index': 28, 'body': '🤨'
    }, 'monocle0': {'index': 29, 'body': '🧐'
    }, 'stuck_out_tongue_closed_eyes0': {'index': 30, 'body': '😝'
    }, 'stuck_out_tongue0': {'index': 31, 'body': '😛'
    }, 'money_mouth_face0': {'index': 32, 'body': '🤑'
    }, 'nerd_face0': {'index': 33, 'body': '🤓'
    }, 'sunglasses0': {'index': 34, 'body': '😎'
    }, 'star_struck0': {'index': 35, 'body': '🤩'
    }, 'clown_face0': {'index': 36, 'body': '🤡'
    }, 'cowboy_hat_face0': {'index': 37, 'body': '🤠'
    }, 'hugs0': {'index': 38, 'body': '🤗'
    }, 'smirk0': {'index': 39, 'body': '😏'
    }, 'no_mouth0': {'index': 40, 'body': '😶'
    }, 'neutral_face0': {'index': 41, 'body': '😐'
    }, 'expressionless0': {'index': 42, 'body': '😑'
    }, 'unamused0': {'index': 43, 'body': '😒'
    }, 'roll_eyes0': {'index': 44, 'body': '🙄'
    }, 'thinking0': {'index': 45, 'body': '🤔'
    }, 'lying_face0': {'index': 46, 'body': '🤥'
    }, 'hand_over_mouth0': {'index': 47, 'body': '🤭'
    }, 'shushing0': {'index': 48, 'body': '🤫'
    }, 'symbols_over_mouth0': {'index': 49, 'body': '🤬'
    }, 'exploding_head0': {'index': 50, 'body': '🤯'
    }, 'flushed0': {'index': 51, 'body': '😳'
    }, 'disappointed0': {'index': 52, 'body': '😞'
    }, 'worried0': {'index': 53, 'body': '😟'
    }, 'angry0': {'index': 54, 'body': '😠'
    }, 'rage0': {'index': 55, 'body': '😡'
    }, 'pensive0': {'index': 56, 'body': '😔'
    }, 'confused0': {'index': 57, 'body': '😕'
    }, 'slightly_frowning_face0': {'index': 58, 'body': '🙁'
    }, 'frowning_face0': {'index': 59, 'body': '☹'
    }, 'persevere0': {'index': 60, 'body': '😣'
    }, 'confounded0': {'index': 61, 'body': '😖'
    }, 'tired_face0': {'index': 62, 'body': '😫'
    }, 'weary0': {'index': 63, 'body': '😩'
    }, 'pleading0': {'index': 64, 'body': '🥺'
    }, 'triumph0': {'index': 65, 'body': '😤'
    }, 'open_mouth0': {'index': 66, 'body': '😮'
    }, 'scream0': {'index': 67, 'body': '😱'
    }, 'fearful0': {'index': 68, 'body': '😨'
    }, 'cold_sweat0': {'index': 69, 'body': '😰'
    }, 'hushed0': {'index': 70, 'body': '😯'
    }, 'frowning0': {'index': 71, 'body': '😦'
    }, 'anguished0': {'index': 72, 'body': '😧'
    }, 'cry0': {'index': 73, 'body': '😢'
    }, 'disappointed_relieved0': {'index': 74, 'body': '😥'
    }, 'drooling_face0': {'index': 75, 'body': '🤤'
    }, 'sleepy0': {'index': 76, 'body': '😪'
    }, 'sweat0': {'index': 77, 'body': '😓'
    }, 'hot0': {'index': 78, 'body': '🥵'
    }, 'cold0': {'index': 79, 'body': '🥶'
    }, 'sob0': {'index': 80, 'body': '😭'
    }, 'dizzy_face0': {'index': 81, 'body': '😵'
    }, 'astonished0': {'index': 82, 'body': '😲'
    }, 'zipper_mouth_face0': {'index': 83, 'body': '🤐'
    }, 'nauseated_face0': {'index': 84, 'body': '🤢'
    }, 'sneezing_face0': {'index': 85, 'body': '🤧'
    }, 'vomiting0': {'index': 86, 'body': '🤮'
    }, 'mask0': {'index': 87, 'body': '😷'
    }, 'face_with_thermometer0': {'index': 88, 'body': '🤒'
    }, 'face_with_head_bandage0': {'index': 89, 'body': '🤕'
    }, 'woozy0': {'index': 90, 'body': '🥴'
    }, 'sleeping0': {'index': 91, 'body': '😴'
    }, 'zzz0': {'index': 92, 'body': '💤'
    }, 'poop0': {'index': 93, 'body': '💩'
    }, 'smiling_imp0': {'index': 94, 'body': '😈'
    }, 'imp0': {'index': 95, 'body': '👿'
    }, 'japanese_ogre0': {'index': 96, 'body': '👹'
    }, 'japanese_goblin0': {'index': 97, 'body': '👺'
    }, 'skull0': {'index': 98, 'body': '💀'
    }, 'ghost0': {'index': 99, 'body': '👻'
    }, 'alien0': {'index': 100, 'body': '👽'
    }, 'robot0': {'index': 101, 'body': '🤖'
    }, 'smiley_cat0': {'index': 102, 'body': '😺'
    }, 'smile_cat0': {'index': 103, 'body': '😸'
    }, 'joy_cat0': {'index': 104, 'body': '😹'
    }, 'heart_eyes_cat0': {'index': 105, 'body': '😻'
    }, 'smirk_cat0': {'index': 106, 'body': '😼'
    }, 'kissing_cat0': {'index': 107, 'body': '😽'
    }, 'scream_cat0': {'index': 108, 'body': '🙀'
    }, 'crying_cat_face0': {'index': 109, 'body': '😿'
    }, 'pouting_cat0': {'index': 110, 'body': '😾'
    }, 'palms_up0': {'index': 111, 'body': '🤲'
    }, 'raised_hands0': {'index': 112, 'body': '🙌'
    }, 'clap0': {'index': 113, 'body': '👏'
    }, 'wave0': {'index': 114, 'body': '👋'
    }, 'call_me_hand0': {'index': 115, 'body': '🤙'
    }, '+10': {'index': 116, 'body': '👍'
    }, '-10': {'index': 117, 'body': '👎'
    }, 'facepunch0': {'index': 118, 'body': '👊'
    }, 'fist0': {'index': 119, 'body': '✊'
    }, 'fist_left0': {'index': 120, 'body': '🤛'
    }, 'fist_right0': {'index': 121, 'body': '🤜'
    }, 'v0': {'index': 122, 'body': '✌'
    }, 'ok_hand0': {'index': 123, 'body': '👌'
    }, 'raised_hand0': {'index': 124, 'body': '✋'
    }, 'raised_back_of_hand0': {'index': 125, 'body': '🤚'
    }, 'open_hands0': {'index': 126, 'body': '👐'
    }, 'muscle0': {'index': 127, 'body': '💪'
    }, 'pray0': {'index': 128, 'body': '🙏'
    }, 'foot0': {'index': 129, 'body': '🦶'
    }, 'leg0': {'index': 130, 'body': '🦵'
    }, 'handshake0': {'index': 131, 'body': '🤝'
    }, 'point_up0': {'index': 132, 'body': '☝'
    }, 'point_up_20': {'index': 133, 'body': '👆'
    }, 'point_down0': {'index': 134, 'body': '👇'
    }, 'point_left0': {'index': 135, 'body': '👈'
    }, 'point_right0': {'index': 136, 'body': '👉'
    }, 'fu0': {'index': 137, 'body': '🖕'
    }, 'raised_hand_with_fingers_splayed0': {'index': 138, 'body': '🖐'
    }, 'love_you0': {'index': 139, 'body': '🤟'
    }, 'metal0': {'index': 140, 'body': '🤘'
    }, 'crossed_fingers0': {'index': 141, 'body': '🤞'
    }, 'vulcan_salute0': {'index': 142, 'body': '🖖'
    }, 'writing_hand0': {'index': 143, 'body': '✍'
    }, 'selfie0': {'index': 144, 'body': '🤳'
    }, 'nail_care0': {'index': 145, 'body': '💅'
    }, 'lips0': {'index': 146, 'body': '👄'
    }, 'tooth0': {'index': 147, 'body': '🦷'
    }, 'tongue0': {'index': 148, 'body': '👅'
    }, 'ear0': {'index': 149, 'body': '👂'
    }, 'nose0': {'index': 150, 'body': '👃'
    }, 'eye0': {'index': 151, 'body': '👁'
    }, 'eyes0': {'index': 152, 'body': '👀'
    }, 'brain0': {'index': 153, 'body': '🧠'
    }, 'bust_in_silhouette0': {'index': 154, 'body': '👤'
    }, 'busts_in_silhouette0': {'index': 155, 'body': '👥'
    }, 'speaking_head0': {'index': 156, 'body': '🗣'
    }, 'baby0': {'index': 157, 'body': '👶'
    }, 'child0': {'index': 158, 'body': '🧒'
    }, 'boy0': {'index': 159, 'body': '👦'
    }, 'girl0': {'index': 160, 'body': '👧'
    }, 'adult0': {'index': 161, 'body': '🧑'
    }, 'man0': {'index': 162, 'body': '👨'
    }, 'woman0': {'index': 163, 'body': '👩'
    }, 'blonde_man0': {'index': 164, 'body': '👱'
    }, 'bearded_person0': {'index': 165, 'body': '🧔'
    }, 'older_adult0': {'index': 166, 'body': '🧓'
    }, 'older_man0': {'index': 167, 'body': '👴'
    }, 'older_woman0': {'index': 168, 'body': '👵'
    }, 'man_with_gua_pi_mao0': {'index': 169, 'body': '👲'
    }, 'woman_with_headscarf0': {'index': 170, 'body': '🧕'
    }, 'man_with_turban0': {'index': 171, 'body': '👳'
    }, 'policeman0': {'index': 172, 'body': '👮'
    }, 'construction_worker_man0': {'index': 173, 'body': '👷'
    }, 'guardsman0': {'index': 174, 'body': '💂'
    }, 'male_detective0': {'index': 175, 'body': '🕵'
    }, 'mrs_claus0': {'index': 176, 'body': '🤶'
    }, 'santa0': {'index': 177, 'body': '🎅'
    }
}
export const emojiKeys = Object.keys(emoji)

export const emojiLen = emojiKeys.length

export const getEmojiByIndex = (index) => {
	return emoji[emojiKeys[index]].body
}

export const emojiContentParse = (content) => {
	const emojiReg = /\[.*?_(\d+?)\]/g
	return content.replace(emojiReg, (match, index) => {
		if(index<0 || index >= emojiLen) return match
		return emoji[emojiKeys[index]].body
	})
}
